grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 1
model_selection:
  module_0:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      criterion: gini
    search_param_grid:
      max_depth:
      - 3
      - 4
      - 5
      min_samples_split:
      - 2
      - 3
      min_samples_leaf:
      - 2
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      criterion: gini
    search_param_grid:
      max_depth:
      - 3
      - 4
      - 5
      min_samples_split:
      - 2
      - 3
      min_samples_leaf:
      - 2
      